name: Pipeline Checks
on:
  push:
    branches: 
    - testHome
jobs:
  format-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x 
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run Format Check
      run: make check-format
    - name: Vet
      run: go vet ./... # <1>
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2 
  test:
    name: Test Application
    needs:
      - format-check
      - lint
    runs-on: ubuntu-latest 
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.20
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run Test
      run: make test 
    - name: Coverage Check
      run: make coverage 
    - name: Generate Report
      run: make report 
    - name: Copy Files
      run: |
        mkdir  reports
        cp cover.html reports/.

    - name: Archive 
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: ./reports 
  